### PR TITLE
Add true system-wide installation method

### PR DESCRIPTION
**Pull request by yitzchak**
This PR adds a system-wide installation method based on [Quicklisp bundles](https://www.quicklisp.org/beta/bundles.html).

- [x] Add class based install
- [x] Add quicklisp bundles
- [x] Add `local-projects` option for bundles
- [x] Update CI

### CODE REVIEW

**Comment by yitzchak** [comment]
@robert-dodier Not sure if you have been following this PR at all, so I'll fill you in a bit. It's still a work in progress but I am getting close. I have a parallel branch that I am working on for Maxima-Jupyter and I just managed to get *system-wide install* method working. From the user perspective this would look like this:

```maxima
load("load-maxima-jupyter.lisp");
jupyter_install(true,"pkg/");
```

Followed by
```sh
sudo cp -r ./pkg/* /
```

Basically I have three different install methods:
1. User install based on image: `jupyter_install_image();`
2. User install based on quicklisp: `jupyter_install();`
3. System install based on quicklisp bundles. User does not need quicklisp installed or configured.

Also of note is the fact that there do not appear to be any `.deb` packages for Ubuntu that Maxima-Jupyter will work with. The distribution packages appear to use GCL which we already know doesn't work, or maybe ECL which is just horrendously slow even for common-lisp-jupyter. Even the nightlies from Maxima's PPA don't appear to work because they use an old SBCL/ASDF combination which can't even load the modern ASD files that Quicklisp is using. In the end I had to build from source.

**Comment by yitzchak** [comment]
@robert-dodier I am pretty much done with this PR if you want to take a look at it. There is a corresponding PR robert-dodier/maxima-jupyter#63 which needs some work on documentation and will need this PR to be available in Quicklisp before it can me merged.

**Comment by robert-dodier** [comment]
Tarn, many thanks for your work on this PR. Installation is always an important problem so any progress on that front is very helpful. Let me take a few minutes to review the commits in this PR.

**Comment by yitzchak** [comment]
@robert-dodier Take your time. You can ignore the changes to the MarkDown files in `docs`

**Comment by yitzchak** [comment]
@robert-dodier This PR is definitely done. Any chance you can take a look? Again, you can ignore the changes to the MarkDown files since that is just a documentation update.

**Comment by robert-dodier** [comment]
Hi Tarn, thanks for the invitation to review this branch. I have glanced at the changes and as far as I understand it, it seems to make sense to me. If there is anything you want me to look closer at, I'll be glad to do so, but on the whole it seems fine to me.

**Comment by yitzchak** [comment]
@robert-dodier Thanks Robert. Once the changes are available in Quicklisp then I'll finalize the matching PR for maxima-jupyter

**Pull request merged**
